### PR TITLE
Allow processing of other file types

### LINKED ISSUE #4: Would you consider an update to also run Converters::PostCss on .scss files?
I was looking for a solution to add auto-prefixing while also working with SCSS files. I have all my SCSS partials compiling into a single CSS file as I'm importing them all in `/assets/css/main.scss`.

Given this jekyll-postcss plugin only runs `Converters::PostCss` on `.css` files I copied the code from `postcss.rb` directly to my `_plugins` directory with one small tweak, changing this line: https://github.com/mhanberg/jekyll-postcss/blob/master/lib/jekyll/converters/postcss.rb#L21 to the following:
```
ext.casecmp(".css").zero? || ext.casecmp(".scss").zero?
```

That change ensures the converter correctly adds auto-prefixing to the CSS file generated from `/assets/css/main.scss` (the final file is created at `/assets/css/main.css` as per usual). It seems to all be working fine, but if you're happy to help I'd love to know:

1. Are there any glaring problems with this approach?
2. Is there a better way to achieve the same result?
3. If no to points 1 and 2, would you consider adding that change to this gem?

Cheers for all your work on this gem, and thanks in advance for any help you're able to offer to those three questions above!

### PR DESCRIPTION
**Pull request by mhanberg**
Closes #4

### CODE REVIEW

**Comment by mhanberg** [comment]
@coreyaus would you mind checking if this fits your use case?

**Comment by coreyaus** [comment]
Thanks @mhanberg! It looks like that'll suit my use case perfectly, and definitely very handy to have it available as an optional setting in the config. Massive thanks for working that request into the plugin, and have an excellent week! 🍻

**Comment by mhanberg** [comment]
Cool, I’ll throw together an example repo to test this out and see if I can’t get this merged sometime this week.

**Comment by pedropalau** [comment]
It would be nice to have this feature in production. I'm working with Tailwind and this feature could make the difference.

**Pull request merged**
